import sklearn.metrics as metrics
import matplotlib.pyplot as plt
import json

import pdb

y_true = []  # ground truth labels
y_probas = []  # predicted probabilities generated by sklearn classifier

with open('iou.json') as f:
    res = json.load(f)
    for el in res:
        iou = el['iou']
        prob = el['score']

        if iou >= 0.5:
            y_true.append(1)
        else:
            y_true.append(0)
        y_probas.append(prob)

fpr, tpr, threshold = metrics.roc_curve(y_true, y_probas)
roc_auc = metrics.auc(fpr, tpr)


plt.title('Receiver Operating Characteristic')
plt.plot(fpr, tpr, 'b', label='AUC = %0.2f' % roc_auc)
plt.legend(loc='lower right')
plt.plot([0, 1], [0, 1], 'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()
